### PR TITLE
Support IEEE 802.1X and more

### PR DESCRIPTION
**Pull request by mkht**
I was looking for a way to manage WiFi profiles using PowerShell DSC, I found this module.
The concept and implementation of this module is very impressed for me.
However, DSC resources were not implemented, so I made it myself.

~~Besides adding DSC resources,~~ I made some improvements, including support for IEEE 802.1X authentication profile.

I would be happy if you merge this PR. 😋 

#### ~~Added DSC resource 'WiFiProfile'~~
  - ~~This resource can manage WiFi profiles.~~

#### Added support for create IEEE 802.1X EAP network profile.
  - Currently supported "PEAP" (aka MSCHAPv2) and "TLS" only.
  - Added `EAPType`, `ServerNames`, `TrustedRootCA` parameter in New/Set-WiFiProfile.
  - Added these properties to `ProfileInfo` class.
  - Changed how to generate XML for WiFi profile.
 
#### Misc improvements
  - Added `ConnectHiddenSSID` parameter in New/Set-WiFiProfile.
    This param indicates whether the profile can connect to networks which does not broadcast SSID.

  - Improved error handling
    - Better error message for the system that has no wireless network interface.
    - Fixed an issue that Remove-WiFiProfile throws error when the multiple objects input from pipeline.

  - Remove code redundancies in Set-WiFiProfile
    In order to improve code maintainability, I changed Set-WiFiProfile to call New-WiFiProfile with just an overwrite flag.

  - Other misc improvements / fixes
    - Added 'SSID' and 'Name' aliases of the 'ProfileName' in New/Set-WiFiProfile.
    - Added ValiableSet attributes to `Authentication` and `Encryption` params.
    - The name of functions to be exported explicitly in the module manifest.
      This change fixes issue that functions not exported when the module is imported implicitly.  
    - Correct typos
 
 #### Update documents in the README
  - Added description of undocumented functions.
  - ”Version" section moved the bottom.
  - Sorted the list of versions in descending order.

---
This change is [Reviewable](https://reviewable.io/reviews/jcwalker/wifiprofilemanagement/22)

### CODE REVIEW

**Comment by mkht** [comment]
@jcwalker Thank you for your reply.

> Are you able to maintain the DSC resource and simply have WiFiProfileManagement as dependancy?

Somewhat disappointing, But I understood your thought.
I will create a DSC resource only module (WiFiProfileManagementDsc) in my repository.
Create a prototype for the module and remove the DSC resource code from this PR so please give me some time.

**Comment by mkht** [comment]
The DSC resource have been removed.

And, I created DSC module **WiFiProfileManagementDsc** in my repo.
https://github.com/mkht/WiFiProfileManagementDsc

**Comment by jcwalker** [comment]
@mkht Awesome!  It will probably be this weekend before I can get to this.  Again, thanks for the contribution!

**Comment by jcwalker** [comment]
@mkht this is really awesome work!  I started this module as a side project in my free time and you made it production ready.  The only thing I ask of you is, can you either change this PR to merge into my dev branch (not sure if this is possible), or close this PR and reopen a new one that merges into my dev branch?  Once that is done I'll get it to the gallery.  Thanks again for your contribution!

**Comment by mkht** [comment]
@jcwalker I changed the target brach to dev. 👍

**Pull request merged**
